apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  #namespace : wordpress-example
  labels:
    app: wordpress
spec:
  type : ClusterIP
  ports:
  - name : mysql
    port: 3306
    targetPort : 3306
  selector:
    app: wordpress
    tier: mysql
  #clusterIP: None


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      nodeSelector:
        type: 'wp'
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        env:
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        # - name: MYSQL_DATABASE
        #   value: wordpress
        - name: MYSQL_USER
          value: root
        #- name :
        - name: MYSQL_ROOT_PASSWORD
          value: aStr0ngPassW0rd
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name : mysql-persistent-storage
          emptyDir: {}
      # - name: mysql-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pv-claim
